# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - rustup default {{ .Env.RUST_VERSION }}

builds:
  - id: cyanprint
    binary: cyanprint
    builder: rust
    tool: cross
    command: build
    flags:
      - --release
      - --all-features
      - -p=cyanprint
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    targets:
      - x86_64-unknown-linux-gnu
      - x86_64-apple-darwin
      - x86_64-pc-windows-gnu
      - aarch64-unknown-linux-gnu
      - aarch64-apple-darwin

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

brews:
  - name: cyanprint
    url_template: 'https://github.com/AtomiCloud/sulfone.iridium/releases/download/{{ .Tag }}/{{ .ArtifactName }}'
    commit_author:
      name: Ernest Ng
      email: kirinnee97@gmail.com
    directory: Formula
    commit_msg_template: 'update({{ .ProjectName }}): to {{ .Tag }}'
    homepage: 'https://cyanprint.dev'
    description: 'Next-Generation Language-Agnostic Templating Platform'
    skip_upload: false
    repository:
      owner: AtomiCloud
      name: homebrew-tap
      branch: main
      token: '{{ .Env.SCOOP_BREW_TOKEN }}'

nfpms:
  - vendor: AtomiCloud
    homepage: https://cyanprint.dev/
    maintainer: Ernest Ng <kirinnee97@gmail.com>

    # Your app's description.
    description: |-
      Next-Generation Language-Agnostic Templating Platform

    license: MIT
    ids:
      - cyanprint
    meta: false
    formats:
      - apk
      - deb
      - rpm
      - termux.deb # Since: v1.11
      - archlinux # Since: v1.13
scoops:
  - name: cyanprint
    url_template: 'https://github.com/AtomiCloud/sulfone.iridium/releases/download/{{ .Tag }}/{{ .ArtifactName }}'
    directory: bucket
    commit_author:
      name: Ernest Ng
      email: kirinnee97@gmail.com
    commit_msg_template: 'update({{ .ProjectName }}): to {{ .Tag }}'
    homepage: 'https://cyanprint.dev'
    description: 'Next-Generation Language-Agnostic Templating Platform'
    skip_upload: false
    repository:
      owner: AtomiCloud
      name: scoop-bucket
      branch: main
      token: '{{ .Env.SCOOP_BREW_TOKEN }}'
checksum:
  name_template: 'checksums.txt'
