# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: cyanprint

builds:
  - id: cyanprint
    main: goreleaser.go
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: cyanprint
    hooks:
      post:
        - ./scripts/goreleaser-shim.sh {{ .Arch }} {{ .Os }} {{ .ProjectName }}

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

brews:
  - name: cyanprint
    url_template: 'https://github.com/AtomiCloud/sulfone.iridium/releases/download/{{ .Tag }}/{{ .ArtifactName }}'
    commit_author:
      name: Ernest Ng
      email: kirinnee97@gmail.com
    directory: Formula
    commit_msg_template: 'update({{ .ProjectName }}): to {{ .Tag }}'
    homepage: 'https://cyanprint.dev'
    description: 'Next-Generation Language-Agnostic Templating Platform'
    skip_upload: false
    repository:
      owner: AtomiCloud
      name: homebrew-tap
      branch: main
      token: '{{ .Env.SCOOP_BREW_TOKEN }}'

nfpms:
  - vendor: AtomiCloud
    homepage: https://cyanprint.dev/
    maintainer: Ernest Ng <kirinnee97@gmail.com>

    # Your app's description.
    description: |-
      Next-Generation Language-Agnostic Templating Platform

    license: MIT
    ids:
      - cyanprint
    meta: false
    formats:
      - apk
      - deb
      - rpm
      - termux.deb # Since: v1.11
      - archlinux # Since: v1.13
checksum:
  name_template: 'checksums.txt'
