version: '3'

vars:
  PLATFORM: sulfone
  SERVICE: iridium

dotenv:
  - .env

tasks:
  build:
    desc: 'Build the binary'
    cmds:
      - cargo build --release
  run:
    desc: 'Run the application'
    cmds:
      - cargo run {{.CLI_ARGS}}
  lint:
    desc: 'Lint the code'
    cmds:
      - pre-commit run --all-files
  e2e:
    desc: 'Run the e2e tests'
    cmds:
      - ./e2e/e2e.sh
