version: '3'

vars:
  PLATFORM: sulfone
  SERVICE: iridium

tasks:
  build:
    desc: 'Build the binary'
    cmds:
      - cargo build --release
  run:
    desc: 'Run the application'
    cmds:
      - cargo run {{.CLI_ARGS}}
