name: CI

on:
  push:

jobs:
  precommit:
    name: Pre-Commit
    uses: ./.github/workflows/⚡reusable-precommit.yaml
    secrets: inherit
    with:
      atomi_platform: sulfone
      atomi_service: iridium

  build:
    name: Build
    uses: ./.github/workflows/⚡reusable-build.yaml
    secrets: inherit
    with:
      atomi_platform: sulfone
      atomi_service: iridium
      bin_name: cyanprint
  publish:
    name: Release CLI
    needs:
      - build
    uses: ./.github/workflows/⚡reusable-cd.yaml
    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '.')
    secrets: inherit
    with:
      atomi_platform: sulfone
      atomi_service: iridium
      namespacelabs: true
