name: CI

on:
  push:

jobs:
  precommit:
    name: Pre-Commit
    uses: ./.github/workflows/⚡reusable-precommit.yaml
    secrets: inherit
    with:
      atomi_platform: sulfone
      atomi_service: iridium

  build:
    name: Build
    uses: ./.github/workflows/⚡reusable-build.yaml
    secrets: inherit
    with:
      atomi_platform: sulfone
      atomi_service: iridium
      rust_version: 1.86.0
      namespacelabs: false
