name: CD

on:
  workflow_call:
    inputs:
      atomi_platform:
        required: true
        type: string
      atomi_service:
        required: true
        type: string
      namespacelabs:
        required: true
        type: boolean

jobs:
  publish:
    name: Release Distribution
    runs-on:
      - nscloud-ubuntu-22.04-amd64-4x8-with-cache
      - nscloud-cache-size-50gb
      - nscloud-cache-tag-${{ inputs.atomi_platform }}-${{ inputs.atomi_service }}-nix-store-cache
    steps:
      # Setup
      - uses: AtomiCloud/actions.setup-nix@v2
        with:
          namespacelabs: ${{ inputs.namespacelabs }}
      - uses: AtomiCloud/actions.cache-cargo@v1
        with:
          namespacelabs: ${{ inputs.namespacelabs }}

      # Publish
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.SCOOP_BREW_TOKEN }}
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
          SCOOP_BREW_TOKEN: ${{ secrets.SCOOP_BREW_TOKEN }}
        run: nix develop .#releaser -c scripts/publish.sh
